name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ===================================================================
      #  الخطوة 4: تثبيت المكتبات (بشكل منفصل وصريح)
      # ===================================================================
      - name: Install Project Dependencies
        working-directory: ./calora
        run: |
          echo "Installing dependencies using the recommended 'npx expo install' command..."
          npx expo install

      # ===================================================================
      #  الخطوة 5: إنشاء ملفات الأندرويد (الآن بعد أن أصبحت المكتبات موجودة)
      # ===================================================================
      - name: Prebuild Android Project
        working-directory: ./calora
        run: |
          echo "Dependencies installed. Starting prebuild process..."
          # الآن يمكننا استخدام --no-install بأمان لأننا قمنا بالتثبيت في الخطوة السابقة
          npx expo prebuild --platform android --no-install

      # ===================================================================
      #  الخطوة 6: بناء ملف الـ APK
      # ===================================================================
      - name: Build Android APK
        working-directory: ./calora/android
        run: |
          echo "Prebuild complete. Building the Android APK..."
          chmod +x ./gradlew
          ./gradlew assembleDebug

      # ===================================================================
      #  الخطوة 7: رفع الناتج
      # ===================================================================
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: calora/android/app/build/outputs/apk/debug/*.apk